python c:/lib/closure/closure-library/closure/bin/closurebuilder.py ^
--root="c:/lib/closure/closure-library/" ^
--root="content/script/live/view/" ^
--root="content/script/live/validation/" ^
--root="content/script/test/view/" ^
--namespace="src.site.validation.validateSocialSecurityNumber" ^
--namespace="src.site.validation.validateText" ^
--namespace="src.site.view.addEmployee" ^
--namespace="src.site.view.editEmployee" ^
--namespace="src.site.view.retrieveBySocialSecurityNumber" ^
--namespace="src.test.view.addEmployee.whenValidatingTheAddEmployeeValues" ^
--namespace="src.test.view.editEmployee.whenValidatingTheEditEmployeeValues" ^
--namespace="src.test.view.retrieveBySocialSecurityNumber.whenValidatingTheRetrieveBySocialSecurityForm" ^
--output_mode=compiled ^
--compiler_jar="c:/lib/closure/compiler.jar" ^
--compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS" ^
--compiler_flags="--externs=content/script/run/jasmine/jasmine.js" ^
--compiler_flags="--externs=content/script/run/jasmine/jasmine-html.js" ^
--compiler_flags="--warning_level=QUIET" ^
--compiler_flags="--generate_exports" > "content/script/run/view/view.js"